trigger:
  branches:
    include:
      - feature/*
  tags:
    include:
      - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Running pipeline for branch or tag: $(Build.SourceBranchName)"
  displayName: "Print the branch or tag name"

